name: PR - Build

on:
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Generar Prisma Client
        run: npx prisma generate

      - name: Compilar proyecto (Next.js)
        env:
          NEXT_TELEMETRY_DISABLED: 1
        run: npm run build
